
# Here we define the parameters used in various scripts.

# Whether to perform the data preprocessing step
preprocess_data: False

# Whether to perform the model training step
train_model: True

# K-means clustering
num_topics: 10

# What data to use?
# raw, cleaned, stemmed
what_data: stemmed

# Names of files and directories

# Raw data
pro_media_dir: raw_data/pro_media.csv
reg_media_dir: raw_data/reg_media.csv

# Translated text
reg_media_translated_dir: data/reg_media_translated.csv
pro_media_translated_dir: data/pro_media_translated.csv

# stopwords removed
pro_media_cleaned_dir: data/pro_media_cleaned_eng.csv
reg_media_cleaned_dir: data/reg_media_cleaned_eng.csv

# stemming of words
pro_media_stemmed_dir: data/pro_media_stemmed_eng.csv
reg_media_stemmed_dir: data/reg_media_stemmed_eng.csv

# Specter model
train_specter2: True




