
# Here we define the parameters used in various scripts.

# Whether to perform the data preprocessing step
preprocess_data: True

# Whether to perform the model training step
train_model: True

# Whether to perform the model evaluation step
Calculate_evaluations: False

# Whether to Visualize data or not 
Create_Visualizations: False


# What data to use?
# raw, cleaned, stemmed
what_data: stemmed

# UMAP, dimensions
umap_dimensions: 2

# Embeddings
embeddings: Merged
#embeddings: Individual

# Hyperparameters for the models:
num_topics: 10
random_state: 42
max_features: 1000
n_top_words: 10

# Number of topic words (bag of words)
nr_words: 6

# Number of summaries
num_summaries: 1

#LDA mode
train_lda: False

# NMF model
train_nmf: False

# Specter model
train_specter2: False

#Bert model
train_bert: False

# Minilm12
train_minilm12: True

# XLM roberta
train_xlm_roberta: True

train_specter2_Actually: True

# Names of files and directories

# Raw data
pro_media_dir: raw_data/pro_media.csv
reg_media_dir: raw_data/reg_media.csv
sci_media_dir: raw_data/sci_media.csv

# Translated text
reg_media_translated_dir: data/reg_media_translated.csv
pro_media_translated_dir: data/pro_media_translated.csv

# stopwords removed
pro_media_cleaned_dir: data/pro_media_cleaned_eng.csv
reg_media_cleaned_dir: data/reg_media_cleaned_eng.csv
sci_media_cleaned_dir: data/sci_media_cleaned_eng.csv

# stemming of words
pro_media_stemmed_dir: data/pro_media_stemmed_eng.csv
reg_media_stemmed_dir: data/reg_media_stemmed_eng.csv
sci_media_stemmed_dir: data/sci_media_stemmed_eng.csv

# Merged stemmed text
merged_stemmed_dir: data/merged_media_stemmed_eng.csv

